### ISSUE TITLE
How to add new layer and filter?

### ISSUE THREAD

**Issue by wahidisna** [nafiesl/laravel-leaflet-example#10]
Hi Nafies.. thanks for this awesome project
I want to know how to add layer or filter based category like restaurant, hotel, etc on the same layer
Thanks

**Comment by nafiesl** [comment]
Hi @wahidisna for map layering options, you might want to check the leaflet js docs in this link https://leafletjs.com/examples/layers-control.

Currently, this project doesn't support it, since the records are just "outlets", not "general places" kind of records. This project is an example for anyone who wants to start working on leaflet js and open street map. Feel free to for this project and make your own. :slightly_smiling_face:
